
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
# ASP.NET Core
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.Billing.csproj'
    feedsToUse: 'select'
    versioningScheme: 'off'

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core